import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "next-themes"
import "./globals.css";
import { Nav } from "@/components/navbar/nav";
import "./fonts/fonts.css"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <ThemeProvider attribute="class" defaultTheme="system"  themes={['light', 'mirage', 'wraith', 'caustic']}>
          <Nav />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
